package com.atz.persistencia;
// Generated 08-ago-2018 21:11:53 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TCliente generated by hbm2java
 */
@Entity
@Table(name = "t_cliente", schema = "public")
public class TCliente implements java.io.Serializable {

	private int oid;
	private TUsuario TUsuario;
	private String nombre;
	private String apellidos;
	private String dni;
	private String direccion;
	private String localidad;
	private String provincia;
	private Integer cp;
	private Integer telefono1;
	private Integer telefono2;
	private String observaciones;
	private String email;
	private Set<TContrato> TContratos = new HashSet<TContrato>(0);
	private Set<TFactura> TFacturas = new HashSet<TFactura>(0);
	private Set<TFactura> TFacturas2 = new HashSet<TFactura>(0);

	public TCliente() {
	}

	public TCliente(int oid) {
		this.oid = oid;
	}

	public TCliente(int oid, TUsuario TUsuario, String nombre, String apellidos, String dni, String direccion,
			String localidad, String provincia, Integer cp, Integer telefono1, Integer telefono2, String observaciones,
			String email, Set<TContrato> TContratos) {
		this.oid = oid;
		this.TUsuario = TUsuario;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.direccion = direccion;
		this.localidad = localidad;
		this.provincia = provincia;
		this.cp = cp;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.observaciones = observaciones;
		this.email = email;
		this.TContratos = TContratos;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_t_usuario")
	public TUsuario getTUsuario() {
		return this.TUsuario;
	}

	public void setTUsuario(TUsuario TUsuario) {
		this.TUsuario = TUsuario;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos")
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "dni")
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "localidad")
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	@Column(name = "provincia")
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "cp")
	public Integer getCp() {
		return this.cp;
	}

	public void setCp(Integer cp) {
		this.cp = cp;
	}

	@Column(name = "telefono1")
	public Integer getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(Integer telefono1) {
		this.telefono1 = telefono1;
	}

	@Column(name = "telefono2")
	public Integer getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(Integer telefono2) {
		this.telefono2 = telefono2;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCliente")
	public Set<TContrato> getTContratos() {
		return this.TContratos;
	}

	public void setTContratos(Set<TContrato> TContratos) {
		this.TContratos = TContratos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCliente")
	public Set<TFactura> getTFacturas() {
		return this.TFacturas;
	}

	public void setTFacturas(Set<TFactura> TFacturas) {
		this.TFacturas = TFacturas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCliente")
	public Set<TFactura> getTFacturas2() {
		return this.TFacturas2;
	}

	public void setTFacturas2(Set<TFactura> TFacturas) {
		this.TFacturas2 = TFacturas;
	}
}
