package com.atz.persistencia;
// Generated 08-ago-2018 21:11:53 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TEstado generated by hbm2java
 */
@Entity
@Table(name = "t_estado", schema = "public")
public class TEstado implements java.io.Serializable {

	private int oid;
	private String descr;
	private Set<TFactura> TFacturas = new HashSet<>(0);

	public TEstado() {
	}

	public TEstado(int oid) {
		this.oid = oid;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "descr")
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCliente")
	public Set<TFactura> getTFacturas() {
		return this.TFacturas;
	}

	public void setTFacturas(Set<TFactura> TFacturas) {
		this.TFacturas = TFacturas;
	}
}
