package com.atz.persistencia;
// Generated 05-oct-2018 13:17:11 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TFacturaLinea generated by hbm2java
 */
@Entity
@Table(name = "t_factura_linea", schema = "public")
public class TFacturaLinea implements java.io.Serializable {

	private int oid;
	private TFactura TFactura;
	private Double cantidad;
	private String descripcion;
	private Double precio;
	private Double descuento;

	public TFacturaLinea() 
	{
		this.descuento = 0D;
	}

	public TFacturaLinea(int oid) {
		this.oid = oid;
	}

	public TFacturaLinea(int oid, TFactura TFactura, Double cantidad, String descripcion, Double precio) {
		this.oid = oid;
		this.TFactura = TFactura;
		this.cantidad = cantidad;
		this.descripcion = descripcion;
		this.precio = precio;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_factura")
	public TFactura getTFactura() {
		return this.TFactura;
	}

	public void setTFactura(TFactura TFactura) {
		this.TFactura = TFactura;
	}

	@Column(name = "cantidad", precision = 17, scale = 17)
	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "precio", precision = 17, scale = 17)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	@Column(name = "descuento", precision = 17, scale = 17)
	public Double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Double descuento) {
		this.descuento = descuento;
	}
}
