package com.atz.persistencia;
// Generated 08-ago-2018 21:11:53 by Hibernate Tools 5.2.11.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TLineaContrato generated by hbm2java
 */
@Entity
@Table(name = "t_linea_contrato", schema = "public")
public class TLineaContrato implements java.io.Serializable {

	private int oid;
	private TAgente TAgente;
	private TContrato TContrato;
	private TPrueba TPrueba;
	private String numeroPlaca;
	private Double capacidad;
	private Date fechaFab;
	private Double precio;
	private Integer cantidad;
	private Date fechaRet;
	private String fabricante;
	private String descr;

	public TLineaContrato() {
	}

	public TLineaContrato(int oid, TAgente TAgente, TContrato TContrato, TPrueba TPrueba, String numeroPlaca,
			Double capacidad, Date fechaFab, Double precio, Integer cantidad, Date fechaRet, String fabricante,
			String descr) {
		this.oid = oid;
		this.TAgente = TAgente;
		this.TContrato = TContrato;
		this.TPrueba = TPrueba;
		this.numeroPlaca = numeroPlaca;
		this.capacidad = capacidad;
		this.fechaFab = fechaFab;
		this.precio = precio;
		this.cantidad = cantidad;
		this.fechaRet = fechaRet;
		this.fabricante = fabricante;
		this.descr = descr;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_t_agente")
	public TAgente getTAgente() {
		return this.TAgente;
	}

	public void setTAgente(TAgente TAgente) {
		this.TAgente = TAgente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_t_contrato")
	public TContrato getTContrato() {
		return this.TContrato;
	}

	public void setTContrato(TContrato TContrato) {
		this.TContrato = TContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_t_prueba")
	public TPrueba getTPrueba() {
		return this.TPrueba;
	}

	public void setTPrueba(TPrueba TPrueba) {
		this.TPrueba = TPrueba;
	}

	@Column(name = "numero_placa")
	public String getNumeroPlaca() {
		return this.numeroPlaca;
	}

	public void setNumeroPlaca(String numeroPlaca) {
		this.numeroPlaca = numeroPlaca;
	}

	@Column(name = "capacidad", precision = 17, scale = 17)
	public Double getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(Double capacidad) {
		this.capacidad = capacidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fab", nullable = false, length = 13)
	public Date getFechaFab() {
		return this.fechaFab;
	}

	public void setFechaFab(Date fechaFab) {
		this.fechaFab = fechaFab;
	}

	@Column(name = "precio", precision = 17, scale = 17)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ret", length = 13)
	public Date getFechaRet() {
		return this.fechaRet;
	}

	public void setFechaRet(Date fechaRet) {
		this.fechaRet = fechaRet;
	}

	@Column(name = "fabricante")
	public String getFabricante() {
		return this.fabricante;
	}

	public void setFabricante(String fabricante) {
		this.fabricante = fabricante;
	}

	@Column(name = "descr")
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

}
