package com.atz.persistencia;
// Generated 10 ago 2023 0:12:16 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TParteCambios generated by hbm2java
 */
@Entity
@Table(name = "t_parte_cambios")
public class TParteCambios implements java.io.Serializable {

	private int oid;
	private TParte TParte;
	private TUsuario TUsuario;
	private Date fecha;

	public TParteCambios() {
	}

	public TParteCambios(int oid, TParte TParte, TUsuario TUsuario, Date fecha) {
		this.oid = oid;
		this.TParte = TParte;
		this.TUsuario = TUsuario;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parte_fk", nullable = false)
	public TParte getTParte() {
		return this.TParte;
	}

	public void setTParte(TParte TParte) {
		this.TParte = TParte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_fk", nullable = false)
	public TUsuario getTUsuario() {
		return this.TUsuario;
	}

	public void setTUsuario(TUsuario TUsuario) {
		this.TUsuario = TUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
