package com.atz.persistencia;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TParteTipo generated by hbm2java
 */
@Entity
@Table(name = "t_parte_periodicidad", schema = "public")
public class TPartePeriodicidad implements java.io.Serializable {

	private int oid;
	private String descripcion;
	private Set<TParte> TPartes = new HashSet<TParte>(0);

	public TPartePeriodicidad() {
	}

	public TPartePeriodicidad(int oid) {
		this.oid = oid;
	}

	public TPartePeriodicidad(int oid, String descripcion, Set<TParte> TPartes) {
		this.oid = oid;
		this.descripcion = descripcion;
		this.TPartes = TPartes;
	}

	@Id
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TParteTipo")
	public Set<TParte> getTPartes() {
		return this.TPartes;
	}

	public void setTPartes(Set<TParte> TPartes) {
		this.TPartes = TPartes;
	}

}
