package com.atz.persistencia;
// Generated 11 nov 2023 18:25:35 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TPicada generated by hbm2java
 */
@Entity
@Table(name = "t_picada", uniqueConstraints = @UniqueConstraint(columnNames = { "fecha", "fk_usuario" }))
public class TPicada 
implements java.io.Serializable 
{
	private int oid;
	private TUsuario TUsuario;
	private Date fecha;
	private Date hini;
	private Date hfin;
	private String info;

	public TPicada() {
	}

	public TPicada(int oid) {
		this.oid = oid;
	}

	public TPicada(int oid, TUsuario TUsuario, Date fecha, Date hini, Date hfin, String info) {
		this.oid = oid;
		this.TUsuario = TUsuario;
		this.fecha = fecha;
		this.hini = hini;
		this.hfin = hfin;
		this.info = info;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_usuario")
	public TUsuario getTUsuario() {
		return this.TUsuario;
	}

	public void setTUsuario(TUsuario TUsuario) {
		this.TUsuario = TUsuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hini", length = 15)
	public Date getHini() {
		return this.hini;
	}

	public void setHini(Date hini) {
		this.hini = hini;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hfin", length = 15)
	public Date getHfin() {
		return this.hfin;
	}

	public void setHfin(Date hfin) {
		this.hfin = hfin;
	}

	@Column(name = "info")
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}
}