package com.atz.persistencia;
// Generated 08-ago-2018 21:11:53 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPreguntas generated by hbm2java
 */
@Entity
@Table(name = "t_preguntas", schema = "public")
public class TPreguntas implements java.io.Serializable {

	private int oid;
	private String descr;
	private Integer oidagente;
	private Set<TPreguntasContrato> TPreguntasContratos = new HashSet<TPreguntasContrato>(0);

	public TPreguntas() {
	}

	public TPreguntas(int oid) {
		this.oid = oid;
	}

	public TPreguntas(int oid, String descr, Integer oidagente, Set<TPreguntasContrato> TPreguntasContratos) {
		this.oid = oid;
		this.descr = descr;
		this.oidagente = oidagente;
		this.TPreguntasContratos = TPreguntasContratos;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "descr")
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name = "oidagente")
	public Integer getOidagente() {
		return this.oidagente;
	}

	public void setOidagente(Integer oidagente) {
		this.oidagente = oidagente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPreguntas")
	public Set<TPreguntasContrato> getTPreguntasContratos() {
		return this.TPreguntasContratos;
	}

	public void setTPreguntasContratos(Set<TPreguntasContrato> TPreguntasContratos) {
		this.TPreguntasContratos = TPreguntasContratos;
	}

	@Override
	public boolean equals(Object obj) 
	{
		TPreguntas p = (TPreguntas) obj;
		
		return this.oid == p.getOid();
	}	
}