package com.atz.persistencia;
// Generated 08-ago-2018 21:11:53 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TPreguntasContrato generated by hbm2java
 */
@Entity
@Table(name = "t_preguntas_contrato", schema = "public")
public class TPreguntasContrato implements java.io.Serializable {

	private int oid;
	private TContrato TContrato;
	private TPreguntas TPreguntas;
	private TPreguntasRespuestas TPreguntasRespuestas;

	public TPreguntasContrato() {
	}

	public TPreguntasContrato(int oid) {
		this.oid = oid;
	}

	public TPreguntasContrato(int oid, TContrato TContrato, TPreguntas TPreguntas,
			TPreguntasRespuestas TPreguntasRespuestas) {
		this.oid = oid;
		this.TContrato = TContrato;
		this.TPreguntas = TPreguntas;
		this.TPreguntasRespuestas = TPreguntasRespuestas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oidcontrato")
	public TContrato getTContrato() {
		return this.TContrato;
	}

	public void setTContrato(TContrato TContrato) {
		this.TContrato = TContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oidpregunta")
	public TPreguntas getTPreguntas() {
		return this.TPreguntas;
	}

	public void setTPreguntas(TPreguntas TPreguntas) {
		this.TPreguntas = TPreguntas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oidrespuesta")
	public TPreguntasRespuestas getTPreguntasRespuestas() {
		return this.TPreguntasRespuestas;
	}

	public void setTPreguntasRespuestas(TPreguntasRespuestas TPreguntasRespuestas) {
		this.TPreguntasRespuestas = TPreguntasRespuestas;
	}

}
