package com.atz.persistencia;
// Generated 08-ago-2018 21:11:53 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TRol generated by hbm2java
 */
@Entity
@Table(name = "t_rol", schema = "public")
public class TRol implements java.io.Serializable {

	private int oid;
	private String descr;
	private Set<TUsuario> TUsuarios = new HashSet<TUsuario>(0);

	public TRol() {
	}

	public TRol(int oid) {
		this.oid = oid;
	}

	public TRol(int oid, String descr, Set<TUsuario> TUsuarios) {
		this.oid = oid;
		this.descr = descr;
		this.TUsuarios = TUsuarios;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "descr")
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRol")
	public Set<TUsuario> getTUsuarios() {
		return this.TUsuarios;
	}

	public void setTUsuarios(Set<TUsuario> TUsuarios) {
		this.TUsuarios = TUsuarios;
	}

}
