package com.atz.persistencia;
// Generated 08-ago-2018 21:11:53 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TUsuario generated by hbm2java
 */
@Entity
@Table(name = "t_usuario", schema = "public")
public class TUsuario implements java.io.Serializable {

	private int oid;
	private TRol TRol;
	private String username;
	private String password;
	private String nombre;
	private String appelidos;
	private Set<TCliente> TClientes = new HashSet<TCliente>(0);

	public TUsuario() {
	}

	public TUsuario(int oid) {
		this.oid = oid;
	}

	public TUsuario(int oid, TRol TRol, String username, String password, Set<TCliente> TClientes) {
		this.oid = oid;
		this.TRol = TRol;
		this.username = username;
		this.password = password;
		this.TClientes = TClientes;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_t_rol")
	public TRol getTRol() {
		return this.TRol;
	}

	public void setTRol(TRol TRol) {
		this.TRol = TRol;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos")
	public String getAppelidos() {
		return appelidos;
	}

	public void setAppelidos(String appelidos) {
		this.appelidos = appelidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUsuario")
	public Set<TCliente> getTClientes() {
		return this.TClientes;
	}

	public void setTClientes(Set<TCliente> TClientes) {
		this.TClientes = TClientes;
	}

}
